version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: sankar-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 53001
      MYSQL_DATABASE: springbankmanagementsystem
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  app:
    build: .
    container_name: sankar-bank
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/springbankmanagementsystem
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 53001

volumes:
  mysql-data: